### ISSUE TITLE
Cythonize doesn't work for purepng from pypi (when Cython is installed)

### ISSUE THREAD

**Issue by frol** [Scondo/purepng#20]
If there is a `cython` available (i.e. installed into a virtualenv), I'm getting the following error:

```
$ pip install purepng
Collecting purepng
  Using cached purepng-0.1.2.1.zip
    Complete output from command python setup.py egg_info:

    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            Scanline modified inplace and also returned as result.
            """
            assert 0 <= filter_type <= 4
            # For the first line of a pass, synthesize a dummy previous line.
            if self.prev is None:
                self.prev = newBarray(len(line))
                                    ^
    ------------------------------------------------------------

    code/png/pngfilters.py:144:33: undeclared name not builtin: newBarray
    Compiling code/png/pngfilters.py because it changed.
    [1/1] Cythonizing code/png/pngfilters.py
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-9ZO15E/purepng/setup.py", line 156, in <module>
        conf['ext_modules'] = cythonize(cyth_ext)
      File "/tmp/env2/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 877, in cythonize
        cythonize_one(*args)
      File "/tmp/env2/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 997, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: code/png/pngfilters.py
```

This error is the same for Python 2.7 and Python 3.5 and appears only when Cython is available and installing from pypi (i.e. `pip install https://github.com/Scondo/purepng/archive/master.zip` works fine!)

**Comment by Scondo** [comment]
Fixed with 0.1.3.
